import { generateShortRunId, generateLongRunId } from './id';
import type { LongRun, ShortRun } from '../types';

export const seedStressTest = (addLongRun: (lr: LongRun) => void, addShortRun: (sr: ShortRun) => void) => {
    const longRunId = generateLongRunId();
    const longRun: LongRun = {
        id: longRunId,
        title: 'Stress Test 2025',
        description: 'Generated by seed script',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        status: 'active',
        color: '#ec4899',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };

    addLongRun(longRun);

    // 5 Overlapping Short Runs (Jan 1 - Jan 15)
    for (let i = 1; i <= 5; i++) {
        addShortRun({
            id: generateShortRunId(),
            longRunId,
            title: `Overlap Phase ${i}`,
            description: 'Testing lane packing',
            startDate: '2025-01-01',
            endDate: '2025-01-15',
            status: 'not_started',
            orderIndex: i,
        });
    }

    // 15 Sequential Short Runs
    for (let i = 0; i < 15; i++) {
        const startMonth = (i % 11) + 1; // 1-12
        const startDay = (i % 28) + 1;
        const startDate = `2025-${String(startMonth).padStart(2, '0')}-${String(startDay).padStart(2, '0')}`;
        // End date 10 days later
        // Simplified date math for seeding
        const endDate = `2025-${String(startMonth).padStart(2, '0')}-${String(startDay + 10).padStart(2, '0')}`;

        addShortRun({
            id: generateShortRunId(),
            longRunId,
            title: `Sequential Phase ${i + 1}`,
            description: 'Testing vertical scrolling',
            startDate,
            endDate,
            status: 'not_started',
            orderIndex: 5 + i + 1,
        });
    }

    return longRunId;
};
